### ISSUE TITLE
React quick start guide

### ISSUE THREAD

**Issue by imagekitio** [imagekit-samples/quickstart#3]
This sample project covers:

- [x] Setting up ImageKit SDK
- [x] Rendering images
- [x] Applying common image manipulations
- [x] Adding overlays to images
- [x] Lazy loading images
- [x] Blurred image placeholder
- [x] Client-side file uploading

The readme should have
- [x] What all the sample project covers
- [x] Link of the quickstart documentation on docs.imagekit.io
- [x] How to run the application locally

**Comment by nikniv** [comment]
Done: https://github.com/imagekit-samples/quickstart/tree/master/react

**Comment by nikniv** [comment]
Marked as complete.
