### ISSUE TITLE
iOS quick start guide

### ISSUE THREAD

**Issue by imagekitio** [imagekit-samples/quickstart#4]
This sample project covers:

- [x] Setting up ImageKit SDK
- [x] Rendering images
- [x] Applying common image manipulations
- [x] Adding overlays to images
- [ ] Lazy loading images
- [ ] Blurred image placeholder
- [x] Client-side file uploading

The readme should have
- [x] What all the sample project covers
- [x] Link of the quickstart documentation on docs.imagekit.io
- [x] How to run the application locally

**Comment by ahnv** [comment]
Lazy Loading and Blurred Image Placeholder will be coming up in the next version of the SDK
